directories:
  dataset_dir: "../head_datasets/ADNI_train_dataset/"
  validation_dataset_dir: "../head_datasets/ADNI_validation_dataset/"
  test_dataset_dir: "../head_datasets/ADNI_test_dataset/"
  results_dir: "./results_CFM_ADNI"
  sample_dir: "./gen_datasets"
  checkpoints_dir: "./results_CFM_ADNI/"

GPU: None # set to None for auto-detection, or specify GPU id as "0", "1"...

checkpoint:
  run: "20260512_174841"
  checkpoint: "117" # step: 117000

parameters:
  epochs: 360 # 400 : 201600, 300 : 151200, 360 : 181440
  batch_size: 8 #4, 8, 16 
  num_workers: 0
  input_size: 128
  num_channels: 64
  num_res_blocks: 2
  in_channels: 2  
  out_channels: 1  
  num_classes: 3  
  save_every: 1000
  lr: 2e-4
  loss_type: "leh"
  warmup_steps: 5000
  lr_scheduler: "cos"
  lr_min: 2e-7
  gamma_decay: 0.9999
  t_max_step: 120000 # for cosine scheduler, can be set to total steps or a smaller value for faster decay
  pl_factor: 0.5
  pl_patience: 500
  update_ema_every: 10
  use_ema: True
  ema_decay: 0.995
  grad_norm: 1.0 
  weight_decay: 1e-4
  val_seeds: [42, 135, 654]

sampling:
  num_samples: 1
  label: "CN"
  seed: 48
  checkpoint: "84"
  run: "20260420_111832"
  ema: True
  mask_id: 941_S_1203 

dataset:
  info_masks:  "../head_datasets/ADNI_test_dataset/diagnosis/test_subjects.csv"
  masks: "../head_datasets/ADNI_test_dataset/mask"
  data_len: 60 # for all = len test dataset
  seed: 42
  num_samples: 3
  checkpoint: "74"
  run: "20260512_174841"

wandb:
  key: 